Fix ASAN build failure with linking nacl_bootstrap.
BUG=463455

FAILED: cd ../../native_client/src/trusted/service_runtime/linux; python ld_bfd.py --compiler g++ -m elf_x86_64 --build-id -static --defsym "RESERVE_TOP=0x0" "--script=nacl_bootstrap.x" -o ../../../../../out/Release/nacl_bootstrap_raw -z "max-page-size=0x1000" --whole-archive ../../../../../out/Release/gen/nacl_bootstrap/libnacl_bootstrap_lib.a --no-whole-archive
../../../../../out/Release/gen/nacl_bootstrap/../../obj/native_client/src/trusted/service_runtime/linux/nacl_bootstrap_lib.nacl_bootstrap.o: In function `do_load':
/mnt/data/b/build/slave/ASAN_Release/build/src/out/Release/../../native_client/src/trusted/service_runtime/linux/nacl_bootstrap.c:547: undefined reference to `__sanitizer_cov'
/mnt/data/b/build/slave/ASAN_Release/build/src/out/Release/../../native_client/src/trusted/service_runtime/linux/nacl_bootstrap.c:547: undefined reference to `__sanitizer_cov'
/mnt/data/b/build/slave/ASAN_Release/build/src/out/Release/../../native_client/src/trusted/service_runtime/linux/nacl_bootstrap.c:551: undefined reference to `__sanitizer_cov'
/mnt/data/b/build/slave/ASAN_Release/build/src/out/Release/../../native_client/src/trusted/service_runtime/linux/nacl_bootstrap.c:551: undefined reference to `__sanitizer_cov'
/mnt/data/b/build/slave/ASAN_Release/build/src/out/Release/../../native_client/src/trusted/service_runtime/linux/nacl_bootstrap.c:566: undefined reference to `__sanitizer_cov'
../../../../../out/Release/gen/nacl_bootstrap/../../obj/native_client/src/trusted/service_runtime/linux/nacl_bootstrap_lib.nacl_bootstrap.o:/mnt/data/b/build/slave/ASAN_Release/build/src/out/Release/../../native_client/src/trusted/service_runtime/linux/nacl_bootstrap.c:566: more undefined references to `__sanitizer_cov' follow
../../../../../out/Release/gen/nacl_bootstrap/../../obj/native_client/src/trusted/service_runtime/linux/nacl_bootstrap_lib.nacl_bootstrap.o: In function `sancov.module_ctor':
../../native_client/src/trusted/service_runtime/linux/nacl_bootstrap.c:(.text.sancov.module_ctor+0x11): undefined reference to `__sanitizer_cov_module_init'
ninja: build stopped: subcommand failed.

NOPRESUBMIT=1
(since CQ+presubmit is currently broken)

Review URL: https://codereview.chromium.org/973803002