PNaCl: Update ARCHIVED_PEXE_TRANSLATOR_REV to fix version skew in testing
Since r9949, the PNaCl toolchain bots fail in the step
"archived_pexe_translator x86-32" with the following error:

crtbegin.o:.../toolchain/pnacl_linux_x86/lib-x86-32/crtbegin.o---crtbegin.c---.po:
function __pnacl_start: error: undefined reference to '_pnacl_wrapper_start'

These tests translate an old copy of "ld.pexe" and drop it into the
current PNaCl toolchain and test whether this combination works.  This
will break whenever internal NaCl interfaces (like syscalls) or
internal PNaCl interfaces change.  The latter changed in r9890 and
r9915 when I made PNaCl's internal interfaces more consistent between
architectures.

BUG=http://code.google.com/p/nativeclient/issues/detail?id=3018
TEST=none (no trybot coverage)

Review URL: https://codereview.chromium.org/11028078

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@9955 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2