Revert r9646: Debug stub: Fix socket binding to coexist with the outer sandbox on Mac
This change has caused the debug stub tests to become flaky on the
Windows bots.  They sometimes fail with:

...
  File "E:\b\build\slave\xp-newlib-opt\build\native_client\tests\debug_stub\gdb_rsp.py", line 62, in _GetReply
    data = self._socket.recv(1024)
error: [Errno 10054] An existing connection was forcibly closed by the remote host

BUG=http://code.google.com/p/nativeclient/issues/detail?id=2879
TEST=none

Review URL: https://chromiumcodereview.appspot.com/10915124

git-svn-id: svn://svn.chromium.org/native_client/trunk/src/native_client@9647 fcba33aa-ac0c-11dd-b9e7-8d5594d729c2