[MIPS] Get rid of "used $at without .set noat" warnings/errors
If assembly code uses $at without explicitly stating ".set noat" before it,
a warning/error will be raised:

tests/common/register_set_test.c:39:7:
error: used $at without ".set noat" [-Werror,-Winline-asm]

This patch removes these warnings.

BUG= several tests fail with nacl-clang due to inline-asm warnings
TEST= ./scons platform=mipsel nacl_clang=1 smoke_tests

Review URL: https://codereview.chromium.org/1275393002